name: API and UI Tests

on: push

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Backend Dependencies (including Cypress & Newman)
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./todofrontend
        run: npm install

      - name: Start Backend and Frontend and Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: |
            npm start &                       # Starts Node server on port 5000
            cd todofrontend && npm run dev &  # Starts React app on port 5137
          wait-on: 'http://localhost:5137,http://localhost:5000'
          wait-on-timeout: 60
          spec: 'cypress/e2e/all.cy.js'

      - name: Run Newman API Tests
        run: npx newman run ./collection.json
